permalink: /:year/:month/:day/:title 

highlighter: pygments

markdown: kramdown

title : Wacky Buttons
tagline: 
author : 
  name : 
  email : 
  github : 
  twitter : 
  web : 

production_url : http://nicholasgunner.com/wackybuttons

baseurl : http://nicholasgunner.com/wackybuttons
        
analytics :
  google : 
    tracking_id :

  
timezone : America/New_York
